version: '3.4'

services:
  qwerty:
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 
    entrypoint: ./entrypoint.sh
    restart: always
    build:
      context: .
      args:
       - UID
    expose:
      - 8000
    volumes:
      - .:/app
    env_file:
      - ./.env
networks:
  default:
      name: main_network
      external: True
